### ISSUE TITLE
no gyro or sensors 

### ISSUE THREAD

**Issue by gazza2577** [rizacelik/STM32F411CEU6_INAV_Firmware#1]
# status
System Uptime: 80 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 8.68V (3S battery - CRITICAL)
CPU Clock=96MHz
STM32 system clocks:
  SYSCLK = 96 MHz
  HCLK   = 96 MHz
  PCLK1  = 48 MHz
  PCLK2  = 96 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=UNAVAILABLE, MAG=UNAVAILABLE, BARO=UNAVAILABLE, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE, IMU2=NONE
Stack size: 6144, Stack address: 0x20020000, Heap available: 2048
I2C Errors: 0, config size: 7049, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = none, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 13, cycle time: 1009, PID rate: 991, RX rate: 49, System rate: 10
Arming disabled flags: ANGLE CAL HWFAIL RX CLI
VTX: not detected

**Comment by rizacelik** [comment]
Hello gazza2577.

Before connecting the GY-87 Module, connect the INAV Configurator to the stm32f411ceu6 black battery board. In the Configuration tab, set the I2C Speed to 800 KHZ. Terminate the connection and connect the  of the GY-87 Module wiring to the diagram.
GYRO, ACC, MAG, BARO will work.

Try it and post the result here.

**Comment by gazza2577** [comment]
# status
System Uptime: 94 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 8.89V (3S battery - CRITICAL)
CPU Clock=96MHz
STM32 system clocks:
  SYSCLK = 96 MHz
  HCLK   = 96 MHz
  PCLK1  = 48 MHz
  PCLK2  = 96 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=UNAVAILABLE, MAG=UNAVAILABLE, BARO=UNAVAILABLE, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE, IMU2=NONE
Stack size: 6144, Stack address: 0x20020000, Heap available: 2048
I2C Errors: 0, config size: 7049, max available config: 16384
ADC channel usage:
   BATTERY : configured = ADC 2, used = ADC 2
      RSSI : configured = none, used = none
   CURRENT : configured = ADC 1, used = none
  AIRSPEED : configured = none, used = none
System load: 13, cycle time: 1006, PID rate: 994, RX rate: 49, System rate: 9
Arming disabled flags: ANGLE CAL HWFAIL RX CLI PWMOUT
VTX: not detected
PWM output init error: Not enough motor outputs/timers

still no joy

**Comment by gazza2577** [comment]
# status
System Uptime: 94 seconds
Current Time: 2041-06-28T01:04:00.000+00:00
Voltage: 8.89V (3S battery - CRITICAL)
CPU Clock=96MHz
STM32 system clocks:
SYSCLK = 96 MHz
HCLK = 96 MHz
PCLK1 = 48 MHz
PCLK2 = 96 MHz
Sensor status: GYRO=UNAVAILABLE, ACC=UNAVAILABLE, MAG=UNAVAILABLE,
BARO=UNAVAILABLE, RANGEFINDER=NONE, OPFLOW=NONE, GPS=NONE, IMU2=NONE
Stack size: 6144, Stack address: 0x20020000, Heap available: 2048
I2C Errors: 0, config size: 7049, max available config: 16384
ADC channel usage:
BATTERY : configured = ADC 2, used = ADC 2
RSSI : configured = none, used = none
CURRENT : configured = ADC 1, used = none
AIRSPEED : configured = none, used = none
System load: 13, cycle time: 1006, PID rate: 994, RX rate: 49, System rate:
9
Arming disabled flags: ANGLE CAL HWFAIL RX CLI PWMOUT
VTX: not detected
PWM output init error: Not enough motor outputs/timers

**Comment by gazza2577** [comment]
still no joy

**Comment by rizacelik** [comment]
Did you follow these steps?

1. First, load the firmware on the STM32F41 board without connecting the modules.
2. Then connect to the board with INAV Configrator.
3. connect the INAV Configurator to the stm32f411ceu6 black battery board.
4. In the Configuration tab, set the I2C Speed to 800 KHZ.
5. Connect the sensor modules to the STM32F41 board.
6. connect the INAV Configurator to the stm32f411ceu6 black battery board.

Have you followed these steps and it didn't work? I can't help you because you haven't given any explanation.

**Comment by gazza2577** [comment]
hi done all above dont think the STM32F41 board. i2c is working .
not sure why would changing the i2c pins help like pin 6 and 7

**Comment by gazza2577** [comment]
Yes, I did.

**Comment by rizacelik** [comment]
With this video, I showed you how to install the sensors. Please watch.

https://youtu.be/HbSUMauSkiw

**Comment by gazza2577** [comment]
getting a new board i followed your video to the letter checked sensors are working on arduino
thanks for your help will let you know how i get on

**Comment by gazza2577** [comment]
hi cant get stm32f411ceu6to work with radio on i bus or s bus
using a Frsky Taranis x9d plus.with fs-ia6b with module plus frsky reciever
using a3 pin rx2 .
do i need to use non-inverted (hacked) sbus
thanks
garry

**Comment by rizacelik** [comment]
You can use frsky reciever. The use of SBUS is turned on, you do not need to do anything additional.

**Comment by gazza2577** [comment]
got it working on frsky rx6r sbus using a diy sbus inverter .
would not work with sbus from receiver.
thanks for all your help
riza
garry

**Comment by rizacelik** [comment]
Great
