### ISSUE TITLE
Compiling/Building

### ISSUE THREAD

**Issue by GatzeTech** [rizacelik/STM32F411CEU6_INAV_Firmware#11]
I'm trying to compile the inav software with your configuration files.

I put it in the directory \src\main\target\STM32F411CE of the inav firmware.

It al works well with the commands 'cmake ..' and make 'STM32F411CE' and get a hexfile (inav_6.0.0_STM32F411CE.hex)

But when I upload it, the board doesn't start, there is also no com port to connect to. But when I upload your hexfile from this github page, everything is working fine, the blue led starts to blink and there is a com port to connect to and I can configurate.

Tried compiling in Linux subsystem for Windows and also Linux it self.

Want to change some pinning, that's why I try to compile myself. Do you know what the problem could be why my compiled hex file with your settings from this page is not working and the precompiled hexfile is ?

Thanks in advance.

PS. there is a slight difference in size from your hexfile (1261 kB) and mine (1257 kB)

**Comment by HKR1987** [comment]
I add pull request with new target blackpill. Take look at 
https://github.com/iNavFlight/inav/pull/8902

**Comment by VaSe7u** [comment]
[HKR1987](https://github.com/HKR1987)'s changes fix the problem.
