### ISSUE TITLE
FrSky receiver

### ISSUE THREAD

**Issue by fabriciosilveira-sjc** [rizacelik/STM32F411CEU6_INAV_Firmware#12]
Hello Riza...

I managed to make the STM32F411 work with Gyro, Acc, Baro and GPS, wow... thanks for the help.

Now I'm installing a FrSky receiver, model XSR.
I installed it as S.BUS on pin A3.
In INAV, in "Ports" I enabled Serial RX on UART 2, in "Receiver", I selected Serial > Sbus. Then I save and restart, and the receiver is not recognized.
I have tested the receiver on the ToolkitRC charger and it works perfectly.

![Ports](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/73246642/380d76e6-23d4-41cd-afa6-bcce3a812ab6)
![Receiver](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/73246642/1951b115-07ae-4108-8c76-fba1413023aa)

**Comment by rizacelik** [comment]
Check the wire connection. It should work.

**Comment by Lalbabu2001** [comment]
> Hello Riza...
> 
> I managed to make the STM32F411 work with Gyro, Acc, Baro and GPS, wow... thanks for the help.
> 
> Now I'm installing a FrSky receiver, model XSR. I installed it as S.BUS on pin A3. In INAV, in "Ports" I enabled Serial RX on UART 2, in "Receiver", I selected Serial > Sbus. Then I save and restart, and the receiver is not recognized. I have tested the receiver on the ToolkitRC charger and it works perfectly.
> 
> ![Ports](https://user-images.githubusercontent.com/73246642/247246062-380d76e6-23d4-41cd-afa6-bcce3a812ab6.PNG) ![Receiver](https://user-images.githubusercontent.com/73246642/247246066-1951b115-07ae-4108-8c76-fba1413023aa.PNG)

Hey did you manages to subs work?
