### ISSUE TITLE
Motor output isn’t working when setup an airplane

### ISSUE THREAD

**Issue by arvet333** [rizacelik/STM32F411CEU6_INAV_Firmware#16]
INAV 6.1.1
Motor output is not working when setup an airplane while working good when you choose copter.
3,3v on motor pin (A8) when airplane is chosen.

Video of problem: https://youtu.be/E0ATdTfJSdY?si=4-UP1_xoSrIfY0L2

when using multishot protocol: https://youtu.be/9gvOiWJdfUk?si=3a30u-wyq4xK0HDG

**Comment by rizacelik** [comment]
### Note: Firmware update. Please download new firmware.

## Step 1
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/e6ae6d0c-dd36-4c65-9e96-2fb0582034a3)

## Step 2
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/a394ead1-a291-4b35-b46e-3ca091ad05a7)

## Step 3
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/563108ce-f69d-4930-a3e2-3d95d04aeabd)

## ## Step 4. Remove batery

## Step 5
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/9c5a8d51-2e76-40b4-b58c-85b7837158c1)

## Step 6. Connect batery

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/f2696883-dce0-44c2-8531-3128b52993af)

# Video


https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/151d1954-da97-4946-a470-9d4456f63009

## Note: Firmware update. Please download new firmware.

**Comment by arvet333** [comment]
Thank you for fixing 🙏

Motors is spinning now, but there is arming flag: ARMING_ DISABLED_PWM_OUTPUT_ERROR

![Arm error](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/80627426/d89e24b1-eed5-43f4-b7ce-25efe148bb33)

**Comment by rizacelik** [comment]
Hello.
It didn't give me such an error either. Flash the firmware again, if the same error occurs again, I will try to fix it.

**Comment by arvet333** [comment]
Reflashed, same error. It will give you this error after all other checks are completed (accelerometer and magnetometer calibrated)

**Comment by rizacelik** [comment]
Ok. I did not calibrate. It's my fault. It will be fixed as soon as possible.

**Comment by arvet333** [comment]
Seems like I accidentally burned my STM board while testing 😢

Hope all is working fine, but I won't be able to fully test until I get a new board delivered.

PS: We lose 1 servo output after this fix, there is no free compatible pins left to assign?
