### ISSUE TITLE
Problem with OSD

### ISSUE THREAD

**Issue by AlexAndryF** [rizacelik/STM32F411CEU6_INAV_Firmware#2]
You specify that the output to the OSD must be taken from PB12. Tell me with which OSD, for example, it will work?

**Comment by rizacelik** [comment]
Hello Alex.

If you look at the STM32F411CEU6 PINOUT Connection header for the OSD, you can find it in the **PIN scheme there**.
You can use OSD development board on the **MAX7456 chip**.
NOTE: I did not do the OSD test, because I do not have the MAX7456 chip. Unfortunately I don't know about this.
You can find the MAX7456 chip at this address. https://kamami.pl/en/retired-products/201502-osd-on-screen-display-module-on-max7456.html

**Comment by AlexAndryF** [comment]
On this module, if change the firmware, can somehow output IBUS telemetry

**Comment by AlexAndryF** [comment]
On this module, if change the firmware, can somehow output IBUS telemetry

**Comment by rizacelik** [comment]
// *************** SPI OSD *****************************
#define USE_MAX7456
#define MAX7456_SPI_BUS         BUS_SPI2
#define MAX7456_CS_PIN          PB12

Compiled according to the above settings. I could not test the OSD output. I don't have the mx7456 module.

**Comment by AlexAndryF** [comment]
I don't have a max7456 either. I thought how nice it would be if I could output the IBUS telemetry and I could see the data readings on the screen of the FLYSKY fs-6 remote control. I know that INAV allows you to do this.  Is it difficult for you to configure the firmware to receive this signal?

**Comment by rizacelik** [comment]
Open SOFTSERIAL from the control panel and use the PB6 pin. B6 pin is TX pin and connect it to Flysky RX pin IBUS-Sensor. It should work. Please test and let me know the result.

**Comment by AlexAndryF** [comment]
Good. The STM32 board should come to me soon and I will try to do so. I will definitely tell you what happened. Thanks.

**Comment by AlexAndryF** [comment]
Hello! The STM32 fee will arrive at the end of the week. I will try to connect and configure. I wanted to find out what settings need to be made in INAV in the Configuration - Other Features tab? And then one STM32 has already blocked. And also, tell me how and how to take readings of voltage and current for telemetry?

**Comment by rizacelik** [comment]
For this, you can look at the INAV MATEKF411SE CONFIG settings. You can find the content by searching the Youtube channel.
Since this is long and only needs to be explained visually, you can learn by researching.

**Comment by AlexAndryF** [comment]
Ok
