### ISSUE TITLE
Motor 4 doesn't recieve signal after activation of gimbal

### ISSUE THREAD

**Issue by Lalbabu2001** [rizacelik/STM32F411CEU6_INAV_Firmware#22]
As soon as i add  s90 servo gimbal the flight controller cuts signal on m4 pin.

**Comment by rizacelik** [comment]
I did not do a gimbal test. Because I've never used it. Unfortunately I don't have it.

Which of the following firmware did you use?
Firmware inav_6.1.1_STM32F411CE.zip OR Firmware inav_6.1.1_STM32F411CE_HEX.zip 

How did you do your installation? Can you give a screenshot? Let me try to help.

**Comment by Lalbabu2001** [comment]
I tested all but version 6.1.0 working great.

**Comment by rizacelik** [comment]
Did it work on these versions? Thank you for the feedback.
Firmware inav_6.1.1_STM32F411CE.zip VEYA Firmware inav_6.1.1_STM32F411CE_HEX.zip

**Comment by Lalbabu2001** [comment]
I didn't tested 6.1.1 because 6.1.0 is fine I am using mpu6500. Is there
anything that activating servo on pin B10 and B1(as per your circuit
diagram) changes the output pin of motor 4 ?

**Comment by rizacelik** [comment]
For INAV 6.10 and earlier the connections are different. Please see "Old version INAV Firmware Full wire connection" towards the bottom of the page. There is only 1 servo there. PB1 pin does not belong to servos. Look carefully.
You need INAV version 6.1.1. Links are located at the top of the page. For multiple servos you should use this version.

**Comment by Lalbabu2001** [comment]
Even if I use only one pin pb1 for servo it still no signal to motor 4.

Does inav 6.1.1 support ppm?

**Comment by rizacelik** [comment]
pin pb1 not servo

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/37e7789b-aac1-4db5-b912-ce1ee18ef87c)

Yes. There is inav 6.1.1 ppm support.

**Comment by Lalbabu2001** [comment]
Alright, if i want blackbox log can i connect micro sd card module because
the flash chip is not available here .

**Comment by rizacelik** [comment]
Please see diagrams. All the information you need is available there. For Blackbox you will need one M25P16 chip. I'm closing the issue here. Enjoy your work.
