### ISSUE TITLE
GPS not working (RED ICON)

### ISSUE THREAD

**Issue by ArshaanTech** [rizacelik/STM32F411CEU6_INAV_Firmware#23]
Hey I am using inav_6.1.1_STM32F411CE_HEX.hex.
The inav configurator shows a red icon for some reason and I think it just isn't working.
Here is the screenshot:
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/85013497/bcb7ab7a-a9d8-434c-b168-d24252a02602)

I have enables GPS in ports at UART1:
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/85013497/31d60f59-79fe-4ce5-a245-6a2ee450736b)

Connections:
```
A15 - RX
B3 - TX
```

**Comment by rizacelik** [comment]
Someone asked before and I downloaded the Firmware file and reinstalled it, just like you. I don't see any problems. Here is the video and screenshots.

Check your cable connections. VCC or GND cable may not be making full contact.
Check your Rx and Tx cables, one of them may not be making full contact. Replace if necessary. It should work.

https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/65bc52f1-d905-4277-b85f-616b2af88bd0

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/475209eb-1508-440f-914f-d88b0c5c0437)
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/4ed8fd36-905a-4b0e-b94c-82356e2613e5)

**Comment by rizacelik** [comment]
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/98661cd7-fbdb-441d-9915-c5e5f5ef36db)

**Comment by ArshaanTech** [comment]
![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/85013497/7ae451ae-58a5-4116-9795-0dcf8f55ce08)
Still not working

**Comment by rizacelik** [comment]
What is the brand of the GPS module?

**Comment by ArshaanTech** [comment]
NEO 6M 0 001

**Comment by rizacelik** [comment]
I also have the NEO 6M GPS and tested the firmware GPS function with it. Test your GPS module with a development board such as Arduino. Find out if it works.
It is not a software related problem. I test everything and publish the firmware. If there was a problem, I would get lots of notifications.
Despite everything, I will test the firmware again tomorrow.

**Comment by ArshaanTech** [comment]
Thank you so much for the amazing firmware sir! I know that you have tested everything and it must work, I think it might be a problem at my place in Bhopal India. The module is working fine with arduino UNO. I will try more things then. Thank you for the help.

**Comment by rizacelik** [comment]
As I promised you, I tested again and this time I installed all the sensors. As you can see on the screen, **GPS** works smoothly.

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/6c15fdae-9ae7-4b8c-8dc3-5aa115fcb35a)

**Comment by ArshaanTech** [comment]
Okayy thank you so much. I'll just use another module and try maybe that helps. I am still not able to work with it but I'll give u a 1000000/10 for efforts bro. Thank you so much .

**Comment by shrinibas7** [comment]
Which uart to select gps after connecting it in b3 and a15

**Comment by rizacelik** [comment]
UART1 ->Sensor ->GPS
