### ISSUE TITLE
ExpressLRS or serial base receiver support? 

### ISSUE THREAD

**Issue by wittzer** [rizacelik/STM32F411CEU6_INAV_Firmware#3]
Thanks for the awesome project! Currently I have expresslrs module on hand and I wish to give it a try. It is serial based TX/RX receiver. may i know where can I wire it?

**Comment by rizacelik** [comment]
PA3 PIN -> RX 

You can also use the SOFTSERIAL_1 pins.

SOFTSERIAL_1_TX_PIN     PB6
SOFTSERIAL_1_RX_PIN     PB7

You need to set the receiver protocol for SOFTSERIAL_1 from the control panel.

**Comment by Agusg666** [comment]
my elrs on pins A2, A3.
vtx tbs smart audio pin B6 for setting power fvp via oled display

**Comment by rizacelik** [comment]
Your explanation is insufficient, I don't understand.

**Comment by Agusg666** [comment]
my assembly expresslrs pin rx tx to pA3 and pA2 Full telemetry seen on my
tx fsi6(build erfly6).
i added oled display scl sda to set the power on vtx to my liking 25mw to
500mw to pin PB6(smart audio) and so far no bugs, it's perfect on inav 4.0
. I don't want it on inav 5.0 , thanks to the inav firmware you made.
Greetings from Indonesia to you and your family, may you always be healthy.


Pada tanggal Min, 5 Jun 2022 22.25, Rıza Çelik ***@***.***>
menulis:
