### ISSUE TITLE
Betaflight 4.5.0 motors not working.

### ISSUE THREAD

**Issue by ArshaanTech** [rizacelik/STM32F411CEU6_INAV_Firmware#32]
Motor outputs are not working...

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/85013497/101fc99a-dbf0-4b4f-a9e7-d04e750bc282)

**Comment by rizacelik** [comment]
OK, I'll look later. Thank you for the notification.

**Comment by rizacelik** [comment]
If you use MPU6050, ARM operation will not occur. You should use MPU9250 or MPU6500. Calibrate these. If you use compasses, calibrate them.
Do the ARM transaction. You cannot turn on the motor output without ARM operation. After activating the motor output, the motors will start to rotate.

Please do these. If the engines do not start after doing these, report them.
I tested it and it works.

**Comment by rizacelik** [comment]
There is also one more detail. Betaflight engine outputs do not work when the battery is not installed. You need to connect the battery while the board is plugged into USB. Be careful not to burn the Borad.
Watch this video.

https://youtu.be/1WYDsiYJGoQ?t=796

**Comment by ArshaanTech** [comment]
it worked as soon as i connected the MPU6500 sensor. Thank you.
