### ISSUE TITLE
Can't change mixer profile

### ISSUE THREAD

**Issue by longlong7211** [rizacelik/STM32F411CEU6_INAV_Firmware#38]

**Comment by rizacelik** [comment]
Which Firmware INAV or BETAFLIGHT?

**Comment by longlong7211** [comment]
INAV, i change profile 1 to 2 and then it restart but profile still 1

**Comment by rizacelik** [comment]
I'm away from home and don't have a chance to test it. You can learn the details by looking at INAV documents.
I would appreciate if you give feedback when you find a solution. Thanks.

**Comment by longlong7211** [comment]
ohh, f411 doesn't support 2 mixer profiles. 
<img width="1037" alt="Screenshot 2024-01-16 at 23 09 46" src="https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/51793029/e3a1cb53-59d0-4b61-b0d0-8ed916759300">
