### ISSUE TITLE
is it possible to access another UART through B6 and B7

### ISSUE THREAD

**Issue by synersignart** [rizacelik/STM32F411CEU6_INAV_Firmware#4]
since the GPS taken up the UART1 A9 & A10TX1RX1 looking that I needed another UART serving as live telemetry
and A2 & A3 Tx2 Rx2 Receiver PPM

I needed another telemetry port open is it possible to use
B11 and B12 of TX6 RX6
or B6 and B7 of Tx1 RX1
how is this mapped out in the board and in the INAV configurator need clarification 

would be nice if you could share the source code of the Build.sh  and Src/Main/Target  so other developers can add fixes to it

**Comment by synersignart** [comment]
also still getting problems of getting the mpu 9250 to work the Gyro, Mag and Acc on occetion the Baro BMP280 goes on and off 
Version 5.0.0

**Comment by Agusg666** [comment]
i try set gyro_hardware_lpf = 188HZ, cpu load 17%

**Comment by synersignart** [comment]
> i try set gyro_hardware_lpf = 188HZ, cpu load 17%

what would be the CLI command for this?

or any source target code I can look so I  can build the implementation . 

please add
MPU9250
MPU6000
AK8960
MMC5883
thanks

**Comment by rizacelik** [comment]
Hi The latest firmware has been recompiled to use the sensors.

**Comment by ahalsaqqa** [comment]
now the firmware supports 3 UART  ports?

**Comment by rizacelik** [comment]
All pins are in use. There are no remaining pins. That's why there is no UART3 support.

**Comment by ahalsaqqa** [comment]
https://os.mbed.com/media/uploads/hudakz/blackpill-pinout.png

the UART6 pins not used I think  PA12 and PA11

**Comment by rizacelik** [comment]
PA11 and PA12 are used for USB. The system will not work when these two pins are used.
