### ISSUE TITLE
GY91 SPI implementation 

### ISSUE THREAD

**Issue by synersignart** [rizacelik/STM32F411CEU6_INAV_Firmware#5]
I plug the board to SPI1
involving Pins A4 A5 A6 A7 
on the GY91 MPU9250 
as INAV implementation for these sensors are on ISP perhaps we can included as SPI sensors and let users plug in these sensors via SPI and retain the MP6050 as I2C
MPU 6000
MPU 6500
MPU 9250
BMI160

some are moving away from the MPU6050 I2C sensor as it its old and prone to Horizon drift ,. 

Solution is to implement the SPI sensors into the Target as these sensors I listed are also available as SPI boards too. why not make use of them.

**Comment by rizacelik** [comment]
Hi The latest firmware has been recompiled to use the sensors.
I do not have ISP supported sensors, but I will add this support in the next firmware.

**Comment by synersignart** [comment]
hmm  can you share the source  as it would be helpful for the INAV community to work bugs out too .  I'll see if i can work this out. also I do need infor on the WS2811 Led strips where did you locate the pins.   also my build now with the help of other community now supports SPI but id good to know that the to have the 6050 available.

**Comment by Agusg666** [comment]
Let me share experience using the mpu6050 gyro160 i2c, during the test of more than 100x stable flights never experienced a significant failure while using the inav Rizacelik firmware, one flight failure using inav 5.0 and caused my frame to break, now I'm trying the gy-87 mpu6050 and gy-6500 with cut all sides of the pcb into small pieces and put a soft mount right on the Stm32f411ceu6 development board chips. sorry I use Google translate.

**Comment by Agusg666** [comment]
Let me share experience using the mpu6050 gyro160 i2c, during the test of more than 100x flights never experienced a significant failure while using the inav Rizacelik firmware, one flight failure using inav 5.0 and caused my frame to break, now I'm trying the gy-87 mpu6050 and gy-6500 by cutting all sides of the pcb became small and put a soft mount right on the Stm32f411ceu6 development board chips. sorry I use Google translate.

**Comment by Agusg666** [comment]
I'm trying to share a channel video with the keyword stm32f411ceu6 INAV gyro pcb cut, sorry I'm not proficient, if you don't like it I'll delete this post

**Comment by Agusg666** [comment]
Let me share my experience using the mpu6050 gyro160 i2c, during the test of more than 100x flights I had a significant failure when using the Rizacelik inav firmware, now I tried the gy -87 mpu6050 and gy-6500 by cutting all sides of the PCB into small pieces and installing the soft stand right on the development board chip STM32f411ceu6. sorry I use Google translate.

**Comment by Agusg666** [comment]
Let me share my experience using the mpu6050 gyro160 i2c, during the test of more than 100x flights never had a significant failure when using the inav Rizacelik firmware, now I tried the gy -87 mpu6050 and gy-6500 by cutting all sides of the PCB into small pieces and installed the soft stand right on the STM32f411ceu6 chip development board. sorry I use Google translate

**Comment by Agusg666** [comment]
Let me share my experience using the mpu6050 gyro160 i2c, during the test of more than 100x flights never had a significant failure when using the inav Rizacelik firmware, now I tried the gy -87 mpu6050 and gy-6500 by cutting all sides of the PCB into small pieces and installed the soft mount right on the STM32f411ceu6 chip development board. sorry I use Google translate

**Comment by synersignart** [comment]
ah finally some update but due to chip market inconsistency on the MPU9250 Ive use the BMI160

**Comment by fabriciosilveira-sjc** [comment]
Hello @rizacelik. The INAV flash was a success of the STM32F411 (Black Pill).
I'm using the GY-91 module, with MPU 9250 and a BMP280.
In Arduino the GY-91 worked perfectly, but in INAV Accel and Gyro are not recognized, what can I do to solve it.
I tried to use all the fw you made available, but without success.
![image](https://user-images.githubusercontent.com/73246642/226366875-28f5fa0f-06f7-4008-8051-8377f545b1b8.png)

**Comment by fabriciosilveira-sjc** [comment]
Hello @rizacelik. The INAV flash was a success of the STM32F411 (Black Pill).
I'm using the GY-91 module, with MPU 9250 and a BMP280.
In Arduino the GY-91 worked perfectly, but in INAV Accel and Gyro are not recognized, what can I do to solve it.
I tried to use all the fw you made available, but without success.
![image](https://user-images.githubusercontent.com/73246642/226367218-7a2e5fa6-f89a-46ff-9d18-a7b000ce317a.png)

**Comment by rizacelik** [comment]
Hello;
You have made the cable connections correctly and the BMP280 seems to be working.
In the Configuration tab you should see the MPU-9250 in the sensor list. Select it if it is in the list.

**Comment by rizacelik** [comment]
Your link is incorrect. See "Full wire connection" on the main page. Uses SPI Sensors cables B12,B13,B14.
![image](https://user-images.githubusercontent.com/19993109/227233061-68cbd7ae-b285-4600-a2d5-4ce4eb6dbc67.png)

**Comment by rizacelik** [comment]
How is your configuration screen? can I see.

**Comment by fabriciosilveira-sjc** [comment]
I'm using version 6.0 of INav.
![image](https://user-images.githubusercontent.com/73246642/227235993-4b1ffd43-1bed-432c-b94f-cb3ae5dd78cb.png)
![image](https://user-images.githubusercontent.com/73246642/227236186-65580167-a9a1-4c0b-bbb6-bad1713839a4.png)
![image](https://user-images.githubusercontent.com/73246642/227236276-3e32c740-45bc-4f40-926d-1ec770fe83bb.png)
![image](https://user-images.githubusercontent.com/73246642/227236361-7b0dd8e8-17b9-4f38-b692-595dbcf77037.png)

**Comment by rizacelik** [comment]
![image](https://user-images.githubusercontent.com/19993109/227237812-7a466c82-0abc-42cb-b284-39c255eb92c5.png)
Is the MPU9250 on this list? 
Or what sensors are there?

**Comment by rizacelik** [comment]
OK GY-91 itis working I2C. No problem.
INAV SPI connected support.
Please select congigrasyon an test.

![image](https://user-images.githubusercontent.com/19993109/227278643-b5a8601b-968c-4a99-9cb8-47513d348b43.png)

**Comment by rizacelik** [comment]
Is your wire connection as follows?

![image](https://user-images.githubusercontent.com/19993109/227309564-877fa6be-4f99-4449-b40c-6179f3cf0a53.png)

**Comment by rizacelik** [comment]
Looks like the AK8963 magnetometer needs to be bypassed. I will work for it and post the result here.

**Comment by fabriciosilveira-sjc** [comment]
Riza, in this GY-91 module, has no magnetometer, only Gyro and Baro.

**Comment by rizacelik** [comment]
I did a recompile, can you test it?
[inav_6.0.0_STM32F411CE.zip](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/files/11060703/inav_6.0.0_STM32F411CE.zip)

**Comment by fabriciosilveira-sjc** [comment]
I tried just now and the PC recognized it as DFU, I flashed it through INAV, but the GY-91 still didn't work.

**Comment by rizacelik** [comment]
Ok.
MPU9250 is set to I2C1, DFU should work. Please test it.

I2C1

SCL  ->       PB8
SDA   ->      PB9

[inav_6.0.0_STM32F411CE.zip](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/files/11062886/inav_6.0.0_STM32F411CE.zip)

**Comment by fabriciosilveira-sjc** [comment]
I made the connection via I2C.
Barometer okay.
I tested all the Acc options, without success.
![image](https://user-images.githubusercontent.com/73246642/227590358-32df16eb-7ff2-4640-85ee-48470d8159fb.png)

**Comment by rizacelik** [comment]
The GY-91 Module is unfortunately seen as MPU9255, not MPU9250. Registers are different.
Necessary warning has been made at this address. https://github.com/ricardozago/GY91-MPU9250-BMP280
I recompiled based on this information, I hope it will be successful this time. Please test and post the result.
[inav_6.0.0_STM32F411CE.zip](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/files/11064975/inav_6.0.0_STM32F411CE.zip)

**Comment by fabriciosilveira-sjc** [comment]
I flashed the new fw.
I tested all MPUs to no avail.
The connection is in I2C.

**Comment by rizacelik** [comment]
What's the result? failed?

**Comment by rizacelik** [comment]
Can you try for the last time?
[inav_6.0.0_STM32F411CE.zip](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/files/11065501/inav_6.0.0_STM32F411CE.zip)

**Comment by fabriciosilveira-sjc** [comment]
Hello Riza, INAV has the Baro symbol in blue (BMP280).
But the Acc didn't work out.
I've tried every version of INAV you sent me.

**Comment by rizacelik** [comment]
I tried a lot but unfortunately it didn't work. It may be chip sourced or the INAV libraries may not be written for it.
I made you test it by changing the registers, but it still didn't work.
Take care of yourselves.

**Comment by fabriciosilveira-sjc** [comment]
It worked...!!!!!!!!
https://user-images.githubusercontent.com/73246642/227620307-c4cc3b31-6a8f-41eb-a06a-8b064ad21ff5.mp4

**Comment by rizacelik** [comment]
It's great, we did it together. :)
Did you use the latest firmware?
If the latest firmware I sent, I will distribute accordingly.

**Comment by synersignart** [comment]
> Riza, in this GY-91 module, has no magnetometer, only Gyro and Baro.
> 
> Sorry so many questions rs

yes oddly the MPU9250 or GY91 has the Gyro and Acc  available in SPI how ever INAV doesnt have the means to get the Mag and Baro in SPI as well in my case I use the seperate Mag and Baro to run i2c

**Comment by synersignart** [comment]
> Hello Riza, I can't put Black Pill in DFU on INAV, the computer doesn't recognize it as STM Bootloader. I made the recording of the new fm that you compiled, via FTDI recorder. But it didn't work. I tried to do it in AUTO, MPU6050, MPU6000, MPU6500 and MPU9250, without success. ![image](https://user-images.githubusercontent.com/73246642/227530882-6f3e4083-ed1a-4133-8ffa-937dc696ad63.png) ![image](https://user-images.githubusercontent.com/73246642/227530979-a0129904-f2e1-4aca-a74f-b57c89bc9d14.png)

1st the BackPill  (Weact Studio warns of Clone Black pills that wont flash or operate as intended) pls not of  sources
2nd the STM32F411 has this weird perk that at 25mhz can cause issues getting in DFU mode the work around is to preheat 25c the chip buy plugging it in for a few mins  before plugging it to attempt to DFU mode. (this the reason most FCs that uses this chip runs with a 24mhz crystal) Blackpill is an oddity that runs on 25mhz

**Comment by synersignart** [comment]
> Hello sinersignart; There are three different MPU9250 modules on the market. WHOMI records are 0x71 , 0x73, and 0x75. INAV only uses the real WHOMI record with 0x71. Other modules are column products. Let's test with you as we did with mr fabriciosilveira-sjc. I recompiled according to the FIRMWARE 0x71 , 0x73, and 0x75 values I will post below. We can get around this problem if you test it and report the result. [inav_6.0.0_STM32F411CE.zip](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/files/11086694/inav_6.0.0_STM32F411CE.zip)

I see , which one was adjusted in the the drivers accgyro_mpu9250.c

**Comment by synersignart** [comment]
where does the file IMU registries are stored in INAV
?

**Comment by synersignart** [comment]
> It's in the gyro_mpu.h file. Did the Firmware I sent sinersignart work?

ah the reason id ask is that  im using our board which has very different Pin assignments hence I required to rebuild the INAV 

so I just change  `#define MPU9250_WHO_AM_I_CONST              (0x71) `

the `#define MPU9255_WHO_AM_I_CONST              (0x73)` might conflict from INAV default?

**Comment by rizacelik** [comment]
Your English is not fully understandable. No, conflict from INAV default.

**Comment by fabriciosilveira-sjc** [comment]
Hello Riza... once again many thanks for your help with connection and firmware for the GY-91.
Another question, does the HC-SR04 signal work with the STM32F411 (Black pill) running INAV 6?

**Comment by fabriciosilveira-sjc** [comment]
> Olá. Sory, preterido, não funcionará com INAV 2.0 e posterior.

OK.
I have two questions:

1. Does STM32F103 (Blue Pill) run INAV 1.7.3? I couldn't make it work. That's for me to try using sonar.

2. Is there a compatible sonar for A STM32F411 (Black Pill)?

**Comment by Lalbabu2001** [comment]
> I tried just now and the PC recognized it as DFU, I flashed it through INAV, but the GY-91 still didn't work.

How did you manage to get back dfu mode mine has same problem after flashing this crappy firmware.
