### ISSUE TITLE
Support for the BMI160 Gyro Acc

### ISSUE THREAD

**Issue by mursa1en** [rizacelik/STM32F411CEU6_INAV_Firmware#54]
Hello, Mr. Celik. Sorry to bother you again.
Do any of these firmware versions support the BMI160? If not, I kindly request that you consider incorporating support for the BMI160. The MPU6000 is no longer available, and the MPU6500 and MPU9250 suffer from increased noise levels. In contrast, the BMI160 overcomes these issues while maintaining a more cost-effective solution.

**Comment by rizacelik** [comment]
I made the change. You can download the file.

**Comment by mursa1en** [comment]
Thanks a lot sir

**Comment by mursa1en** [comment]
![IMG_20240419_190342.jpg](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/108753302/a28d3f8f-22ed-4902-8dca-f63ec76070d0)

This is how i connected the BMI 160. 


Inav is detecting the board as the MPU 6500 and not working. I tried both firmware. The 7.1 and the 7.1 hex

**Comment by rizacelik** [comment]
Pins are correct. If you connected BMI160 but it detects it as MPU6500, this module is fake. INAV detects it automatically. There is no error in INAV.

![image](https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/assets/19993109/a5f25632-12a8-455a-91b7-0fe1e1bd4ba6)
