### ISSUE TITLE
Cannot configure blackbox W25Q128 

### ISSUE THREAD

**Issue by AaronSmith69** [rizacelik/STM32F411CEU6_INAV_Firmware#60]
I tried to flash the fc with inav 6.0, 6.1, 7.0, 7.1 and all got "No dataflash chip found", i even changed other spi port connection but still. Can someone help pls?

**Comment by rizacelik** [comment]
It's been asked before. Look here.
https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware/issues/35
