### ISSUE TITLE
is it possible to remap motor and servo outputs?

### ISSUE THREAD

**Issue by ASADAIDAR** [rizacelik/STM32F411CEU6_INAV_Firmware#8]
I assembled a budget flight controller for a flying wing according to the instructions (3 outputs: 2 servos and 1 motor), but for convenience I need to remap the outputs S1 to pin B3; S2 to pin A8; S3 to pin B4;S6 to pin B10. Could you compile a new firmware with these outputs?I made handy pins (pictured) to connect the servos and motors, so I need to remap the outputs.
![KIONrl26rhc](https://user-images.githubusercontent.com/89451051/196514656-793e5050-2e68-4d5e-972f-faecbace6e11.jpg)
![aEyDT6wr46U](https://user-images.githubusercontent.com/89451051/196514667-74672f0f-36d7-4a0d-ba8a-739f692b7bba.jpg)

**Comment by rizacelik** [comment]
Unfortunately I don't have time for this. 
Sory.

**Comment by rizacelik** [comment]
Everything you will need has been made, why not consider doing it with a few cables. The easiest way is to combine a PCB with a board.
